### ISSUE TITLE
Unable to prepare setup for platform huahuacaocao.sensor

### ISSUE THREAD

**Issue by marekbarczyk** [r-renato/hass-xiaomi-mi-flora-and-flower-care#1]
2019-09-26 09:09:44 ERROR (MainThread) [homeassistant.setup] Error during setup of component huahuacaocao
Traceback (most recent call last):
  File "/home/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 168, in _async_setup_component
    hass, processed_config
  File "/home/homeassistant/.homeassistant/custom_components/huahuacaocao/__init__.py", line 60, in async_setup
    hass.data[DOMAIN][SERVICE_API] = ServiceAPI(config[DOMAIN][CONF_USERNAME], config[DOMAIN][CONF_PASSWORD], config[DOMAIN][CONF_REGION])
KeyError: 'huahuacaocao'

**Comment by r-renato** [comment]
Resolved within v1.0.2
