### ISSUE TITLE
Error while setting up huahuacaocao platform for sensor

### ISSUE THREAD

**Issue by BigDoom** [r-renato/hass-xiaomi-mi-flora-and-flower-care#2]
Trying to use this platform but gives me below message, any ideas?

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 159, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/huahuacaocao/sensor.py", line 175, in setup_platform
    component = EntityComponent(_LOGGER, DOMAIN_PLANT, hass, group_name=GROUP_NAME_ALL_PLANTS)
TypeError: __init__() got an unexpected keyword argument 'group_name'

**Comment by r-renato** [comment]
Hi, yes, I known it.
This is a little bit error  that occurs with the more recent versions of homeassistant.
I have fixed it, if you want you can test the component.
Enjoy.
Renato

**Comment by BigDoom** [comment]
It's working now, thank you!
