### ISSUE TITLE
Error when updating through HACS

### ISSUE THREAD

**Issue by deku-m** [r-renato/hass-xiaomi-mi-flora-and-flower-care#5]
HI,

I get the following error when updating to the new version .
HACS keep mentioning the following:

**__**An error ocoured while processing
startswith first arg must be str or a tuple of str, not NoneType**_ 

Acknowledge_**

Is this something that is on my installation or in the repository combination with HACS.

Thx.

**Comment by r-renato** [comment]
Hi,
the custom component work fine for me.
My levels are:

    HA: 0.105.2
    HACS: 0.22.3
    CC: 3531583

You can try to uninstall and reinstall it, if the error still occur, please put here the relevant log errors.
Thank you,
Renato

**Comment by deku-m** [comment]
Hi,

Update running:
HA 106.6
HACS 0.23.2

Log:

`  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 3 column 1 (char 4)
2020-03-11 07:41:28 INFO (MainThread) [homeassistant.components.automation] Executing themes
2020-03-11 07:41:28 INFO (MainThread) [homeassistant.helpers.script] Script themes: Running script
2020-03-11 07:41:28 INFO (MainThread) [homeassistant.helpers.script] Script themes: Executing step call service
2020-03-11 07:41:28 INFO (MainThread) [homeassistant.components.frontend] Theme dwains-theme-light set as default
2020-03-11 07:41:28 DEBUG (MainThread) [hacs] Running set_state for r-renato/hass-xiaomi-mi-flora-and-flower-care
2020-03-11 07:41:28 DEBUG (MainThread) [hacs.data] Saving data
2020-03-11 07:41:28 DEBUG (MainThread) [hacs] Running install for r-renato/hass-xiaomi-mi-flora-and-flower-care
2020-03-11 07:41:28 DEBUG (MainThread) [hacs.repository.plugin.r-renato.hass-xiaomi-mi-flora-and-flower-care] Getting repository information
2020-03-11 07:41:29 DEBUG (MainThread) [hacs.repository.plugin.r-renato.hass-xiaomi-mi-flora-and-flower-care] Running checks against master
2020-03-11 07:41:35 DEBUG (MainThread) [hacs] Running set_state for r-renato/hass-xiaomi-mi-flora-and-flower-care
2020-03-11 07:41:35 DEBUG (MainThread) [hacs.data] Saving data
2020-03-11 07:41:35 DEBUG (MainThread) [hacs] Running install for r-renato/hass-xiaomi-mi-flora-and-flower-care
2020-03-11 07:41:35 DEBUG (MainThread) [hacs.repository.plugin.r-renato.hass-xiaomi-mi-flora-and-flower-care] Getting repository information
2020-03-11 07:41:36 DEBUG (MainThread) [hacs.repository.plugin.r-renato.hass-xiaomi-mi-flora-and-flower-care] Running checks against master
2020-03-11 07:41:42 DEBUG (MainThread) [hacs] Running set_state for r-renato/hass-xiaomi-mi-flora-and-flower-care
2020-03-11 07:41:42 DEBUG (MainThread) [hacs.data] Saving data
2020-03-11 07:41:42 DEBUG (MainThread) [hacs] Running install for r-renato/hass-xiaomi-mi-flora-and-flower-care
2020-03-11 07:41:42 DEBUG (MainThread) [hacs.repository.plugin.r-renato.hass-xiaomi-mi-flora-and-flower-care] Getting repository information
2020-03-11 07:41:42 DEBUG (MainThread) [hacs.repository.plugin.r-renato.hass-xiaomi-mi-flora-and-flower-care] Running checks against master
2020-03-11 07:41:45 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.gft fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)`


Could be I include a error from different sensor but this is what I can see in the log
I hope you can help else I need to download the plugin and try it manual.

**Comment by r-renato** [comment]
It seems to be a HACS problem. I have update HA to 0.106.6 and reinstalled the custom component without problems.
I don't know how to help you... if I were you, I'd probably reinstall hacs.
```
2020-03-11 10:19:34 DEBUG (SyncWorker_3) [homeassistant.helpers.storage] Writing data for hacs.hacs
2020-03-11 10:19:34 DEBUG (SyncWorker_0) [homeassistant.helpers.storage] Writing data for hacs.removed
2020-03-11 10:19:34 DEBUG (SyncWorker_13) [homeassistant.helpers.storage] Writing data for hacs.repositories
2020-03-11 10:19:37 WARNING (MainThread) [homeassistant.components.device_tracker] Updating device list from legacy took longer than the scheduled scan interval 0:00:12
2020-03-11 10:19:38 INFO (MainThread) [hacs.repository.integration.r-renato.hass-xiaomi-mi-flora-and-flower-care] download of hacs-card-for-xiaomi-mi-flora-and-flower-care.js complete
2020-03-11 10:19:38 INFO (MainThread) [hacs.repository.integration.r-renato.hass-xiaomi-mi-flora-and-flower-care] download of __init__.py complete
2020-03-11 10:19:38 INFO (MainThread) [hacs.repository.integration.r-renato.hass-xiaomi-mi-flora-and-flower-care] download of manifest.json complete
2020-03-11 10:19:38 INFO (MainThread) [hacs.repository.integration.r-renato.hass-xiaomi-mi-flora-and-flower-care] download of sensor.py complete
2020-03-11 10:19:38 DEBUG (SyncWorker_7) [homeassistant.helpers.storage] Writing data for hacs.hacs
2020-03-11 10:19:38 DEBUG (SyncWorker_13) [homeassistant.helpers.storage] Writing data for hacs.removed
2020-03-11 10:19:39 DEBUG (SyncWorker_8) [homeassistant.helpers.storage] Writing data for hacs.repositories
```

**Comment by deku-m** [comment]
MMM its weird as other plugins get installed and updated.
Tried reinstalling but still the same. Maybe workaround could be to do it manual.
DO you maybe now some other debug commands>?

**Comment by r-renato** [comment]
No, the component installation is responsibility of HACS, failures should be reported to HACS.
